name: CI

on:
  push:          # run on every push to any branch
  pull_request:  # and on every PR targeting your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]  # test against several Pythons

    steps:
      # 0) Check out your repository
      - uses: actions/checkout@v4

      # 1) Set up the requested Python version
      - name: Set up Python
        uses: actions/setup-python@v5         # latest major as of 2025 :contentReference[oaicite:0]{index=0}
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"                        # built‑in dependency cache

      # 2) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      # 3) Run your test suite
      - name: Run tests
        run: pytest -v                        # collects everything under tests/