name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      # 0) Check out your repository
      - uses: actions/checkout@v4

      # 1) Set up the requested Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # 2) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      # 3) Check types with MyPy
      - name: Check types with MyPy
        run: mypy --strict .

      # 4) Run your test suite
      - name: Run tests
        run: pytest -v